server:
  port: 8090
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/museum_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: NON_NULL

# 配置日志
logging:
  level:
    root: INFO
    com.museum: DEBUG
    com.museum.mapper: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: PARTIAL
    auto-mapping-unknown-column-behavior: WARNING
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.museum.damain.po
  global-config:
    db-config:
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
      id-type: auto
      field-strategy: not_empty
      with-trigger: false

file:
  uploadPath: D:\uploads\
  staticPath: D:\uploads\**
  baseUrl: http://localhost:8888

knife4j: #开启增强模式
  enable: true
